name: generated
description: generated code.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: ^1.8.2
  generators:
    path: ../generators
  scoute_prime:
    path: ../..
  analyzer: ^5.2.0
  
  

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.14.4
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
