builders:
  scoutingFormGeneratorBuilder:
    import: 'package:generators/builders.dart'
    builder_factories: ['scoutingFormGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".scouting_form.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
